// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/core/data_protocol_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_nearby_connections/flutter_nearby_connections.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/core/services/device_connection_service.dart'
    as _i2;
import 'package:xceleration/core/utils/data_package.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeviceConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceConnectionService extends _i1.Mock
    implements _i2.DeviceConnectionService {
  MockDeviceConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get maxReconnectionAttempts => (super.noSuchMethod(
        Invocation.getter(#maxReconnectionAttempts),
        returnValue: 0,
      ) as int);

  @override
  Duration get rescanBackoff => (super.noSuchMethod(
        Invocation.getter(#rescanBackoff),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#rescanBackoff),
        ),
      ) as Duration);

  @override
  bool get nearbyConnectionsInitialized => (super.noSuchMethod(
        Invocation.getter(#nearbyConnectionsInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  set rescanBackoff(Duration? _rescanBackoff) => super.noSuchMethod(
        Invocation.setter(
          #rescanBackoff,
          _rescanBackoff,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nearbyConnectionsInitialized(bool? _nearbyConnectionsInitialized) =>
      super.noSuchMethod(
        Invocation.setter(
          #nearbyConnectionsInitialized,
          _nearbyConnectionsInitialized,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set receivedDataSubscription(
          _i3.StreamSubscription<dynamic>? _receivedDataSubscription) =>
      super.noSuchMethod(
        Invocation.setter(
          #receivedDataSubscription,
          _receivedDataSubscription,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set deviceMonitorSubscription(
          _i3.StreamSubscription<dynamic>? _deviceMonitorSubscription) =>
      super.noSuchMethod(
        Invocation.setter(
          #deviceMonitorSubscription,
          _deviceMonitorSubscription,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<bool> checkIfNearbyConnectionsWorks(
          {Duration? timeout = const Duration(seconds: 5)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfNearbyConnectionsWorks,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> monitorDevicesConnectionStatus({
    _i3.Future<void> Function(_i4.Device)? deviceFoundCallback,
    _i3.Future<void> Function(_i4.Device)? deviceConnectingCallback,
    _i3.Future<void> Function(_i4.Device)? deviceConnectedCallback,
    Duration? timeout = const Duration(seconds: 60),
    _i3.Future<void> Function()? timeoutCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorDevicesConnectionStatus,
          [],
          {
            #deviceFoundCallback: deviceFoundCallback,
            #deviceConnectingCallback: deviceConnectingCallback,
            #deviceConnectedCallback: deviceConnectedCallback,
            #timeout: timeout,
            #timeoutCallback: timeoutCallback,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> inviteDevice(_i4.Device? device) => (super.noSuchMethod(
        Invocation.method(
          #inviteDevice,
          [device],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> attemptReconnection(_i4.Device? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #attemptReconnection,
          [device],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> disconnectDevice(_i4.Device? device) => (super.noSuchMethod(
        Invocation.method(
          #disconnectDevice,
          [device],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> sendMessageToDevice(
    _i4.Device? device,
    _i5.Package? package,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessageToDevice,
          [
            device,
            package,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> monitorMessageReceives(
    _i4.Device? device, {
    required dynamic Function(
      _i5.Package,
      String,
    )? messageReceivedCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorMessageReceives,
          [device],
          {#messageReceivedCallback: messageReceivedCallback},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  void stopMessageMonitoring(String? token) => super.noSuchMethod(
        Invocation.method(
          #stopMessageMonitoring,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
